apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  serviceAccount: supersa
  containers:
  - args:
    - sleep
    - "3600"
    image: mstelles/multi
    name: multi
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
